up:
	docker compose up -d

down:
	docker compose down

logs:
	docker compose logs -f localstack

bootstrap:
	cd infra-cdk && npm run bootstrap:local

deploy:
	cd infra-cdk && npm run deploy:local

destroy:
	cd infra-cdk && npm run destroy:local
